#############################
#### REQUIRED PARAMETERS ####
#############################

#Provide an output name for the CanID run
run: name_of_run
#Specify the path to, and file (space-delimited) name of, list of samples formatted: LIBRARY SAMPLE_ID PATH
files: config/sample_file_list.tsv
#Specify the path to the CanFam3.1 dog reference genome
path_to_reference_genome: workflow/files/canFam3_withY.fa

#############################
#### OPTIONAL PARAMETERS ####
#############################

#MAPPING
#Enable/disable seed
seed: 1024
#Set edit distance 
edit_dist: 0.01 

#There is only a 2M SNP panel with this release. Future releases may have more.
SNP_panel: 2M
