#############################
#### REQUIRED PARAMETERS ####
#############################

#Provide an output name for the CanID run
run: Inner_Reindeer_Cave
#Specify the path to, and file (space-delimited) name of, list of samples formatted: LIBRARY SAMPLE_ID PATH
files: config/sample_file_list.tsv
#Specify the path to the CanFam3.1 dog reference genome
path_to_reference_genome: /home/lachie/DATA/ref/dog/canFam3_withY.fa

#############################
#### OPTIONAL PARAMETERS ####
#############################

#MAPPING
#Enable/disable seed
seed: 1024
#Set edit distance 
edit_dist: 0.01 

#MTDNA CONSENSUS
#Minimum number of bases needed to call mtDNA base
base_depth: 1
#Minimum consensus need to call mtDNA base
base_con: 0.5

#NJTREE
#Number of threads to use in MAFFT alignment
mafft: 20

#Specify either the 2 million (2M) or 6.5 million (6.5M) SNP reference panel
SNP_panel: 2M